import { site } from "@/lib/site";
import { getAllPostsMeta } from "@/sanity/blog";

/*
 * /blog/rss.xml (Blog Build Spec §5) — the latest 20 published posts, for
 * feed readers and some AI ingestion pipelines. Regenerated by the same
 * 'content' revalidation tag as everything else, so publishing a post
 * updates the feed automatically.
 */
export const revalidate = 3600;

/** XML-escape text so a title with & or < can't break the feed */
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function GET() {
  const posts = (await getAllPostsMeta()).slice(0, 20);
  const now = new Date().toUTCString();

  const items = posts
    .map((post) => {
      const url = `${site.url}/blog/${post.slug}`;
      return `    <item>
      <title>${esc(post.title)}</title>
      <link>${url}</link>
      <guid isPermaLink="true">${url}</guid>
      <description>${esc(post.excerpt)}</description>
      <pubDate>${new Date(post.publishedAt).toUTCString()}</pubDate>
    </item>`;
    })
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>The Sapiens Blog</title>
    <link>${site.url}/blog</link>
    <description>Real help, safety, and what the science says about kindness — written as we build Sapiens.</description>
    <language>en</language>
    <lastBuildDate>${posts.length ? new Date(posts[0].publishedAt).toUTCString() : now}</lastBuildDate>
    <atom:link href="${site.url}/blog/rss.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/rss+xml; charset=utf-8",
      "Cache-Control": "public, max-age=0, s-maxage=3600",
    },
  });
}
